### Default settings for the Accordion Front Behavior
default:
  dmAccordionBehavior:
    defaults: # Default settings for behavior
      inner_target: ''
      theme: default
      event: click_open_close
      colapsable: true
      initialy_open: 1 
      animation: slide
      easing: jswing
      duration: 500
    labels:
      initialy_open: Initialy open      
    helps:
      duration: Duration of the animation in ms
      colapsable: Opening one tab will close others
      initialy_open: Enter index of initialy opened accordion(s) separated with semicolon (;), or nothing for all to be closed.
    themes: 
      default: 'dmAccordionBehaviorPlugin.default' # From assets.yml - U can use a path instead